- name: Create config directory
  file:
    path: /etc/docker/compose/myapp
    state: directory

- name: Copy Demo-application Docker image
  copy:
    src: snorbu.se-demo-application-1.2.tar
    dest: /opt/snorbu.se-demo-application-1.2.tar

- name: Load Demo-application into Docker
  docker_image:
    name: snorbu.se/demo-application
    tag: '1.2'
    source: load
    state: present
    load_path: /opt/snorbu.se-demo-application-1.2.tar

- name: Install Docker-compose configuration
  template:
    src: docker-compose.yaml
    dest: /etc/docker/compose/myapp/docker-compose.yaml
  notify:
    - Restart MyApp


- name: Create systemd unit
  template:
    src: myapp.service
    dest: /etc/systemd/system/myapp.service
  notify:
    - Restart MyApp

- name: Reload Systemd configuration
  systemd:
    daemon_reload: yes

- name: Enable MyApp at startup
  systemd:
    name: myapp
    enabled: yes

- name: Start application
  systemd:
    name: myapp
    state: started
