- name: Add Elasticsearch apt-key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install JDK 11
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Set network host
  lineinfile:
    regex: ^network.host
    line: "network.host: 0.0.0.0"
    path: /etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart Elasticsearch

- name: Set cluster name
  lineinfile:
    regex: ^cluster.name
    line: "cluster.name: logging-cluster"
    path: /etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart Elasticsearch

- name: Set node name
  lineinfile:
    regex: ^node.name
    line: "node.name: logging-cluster-node01"
    path: /etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart Elasticsearch

- name: Set initial master node(s)
  lineinfile:
    regex: ^cluster.initial_master_nodes
    line: "cluster.initial_master_nodes: [logging-cluster-node01]"
    path: /etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart Elasticsearch
 
- name: Enable Elasticsearch at startup
  systemd:
    name: elasticsearch
    enabled: yes
