version: '3'
services:
  proxy:
    image: httpd:2.4
    ports: 
      - 80:80
  app:
    image: snorbu.se/demo-application:1.2
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=json-logger
