#- name: Update all servers
#  hosts: all
#  become: yes
#  become_method: sudo
#  roles:
#    - common

- name: Install centrialized log server
  hosts: logservers
  become: yes
  become_method: sudo
  roles:
    - elasticsearch
    - kibana
  
- name: Install application server
  hosts: appservers
  become: yes
  become_method: sudo
  roles:
    - docker
    - application
    - fluentd
    - logstash
  
