- name: Install Kibana
  apt:
    name: kibana
    state: present


- name: Set server host
  lineinfile:
    regex: ^server.host
    line: "server.host: \"{{ ansible_default_ipv4.address }}\""
    path: /etc/kibana/kibana.yml
  notify:
    - Restart Kiban

- name: Set URI to Elasticsearch
  lineinfile:
    regex: ^elasticsearch.hosts
    line: "elasticsearch.hosts: [\"http://localhost:9200\"]"
    path: /etc/kibana/kibana.yml
  notify:
    - Restart Kiban

- name: Enable Kibana at startup
  systemd:
    name: kibana
    enabled: yes
