- name: Add Elasticsearch apt-key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install Logstash
  apt:
    name: logstash
    state: present

- name: Install example configuration
  template: 
    src: example.conf
    dest: /etc/logstash/conf.d/example.conf
  notify:
    - Restart Logstash

- name: Start Logstash at startup
  systemd:
    name: logstash
    enabled: yes

- name: Start Logstash
  systemd:
    name: logstash
    state: started
